# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsAccessMap < Formula
  desc "Instant 'who can reach this?' mapping for AWS resources"
  homepage "https://github.com/pfrederiksen/aws-access-map"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/aws-access-map/releases/download/v1.0.2/aws-access-map-darwin-x86_64.tar.gz"
      sha256 "dd6a4be051897f8c8d50dacca10a3924df5deed5f2bec05ee69519ef3e224614"

      def install
        bin.install "aws-access-map"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/aws-access-map/releases/download/v1.0.2/aws-access-map-darwin-arm64.tar.gz"
      sha256 "851895c0f9f1680e61b245834fac1086458e6550cd59964a0acaab9856b3242b"

      def install
        bin.install "aws-access-map"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/aws-access-map/releases/download/v1.0.2/aws-access-map-linux-x86_64.tar.gz"
      sha256 "231a4324744b6608b68c057eaa9fa816be50d65c09460374a45473f86b967556"
      def install
        bin.install "aws-access-map"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/aws-access-map/releases/download/v1.0.2/aws-access-map-linux-arm64.tar.gz"
      sha256 "5403d2259c527e125dbb3777ee6067f65bfa6045c9f6b58f47258566dcf13a93"
      def install
        bin.install "aws-access-map"
      end
    end
  end

  test do
    system "#{bin}/aws-access-map --version"
  end
end
