# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlastRadius < Formula
  desc "Local-first AWS dependency graph CLI to understand blast radius before changes"
  homepage "https://github.com/pfrederiksen/blast-radius"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/blast-radius/releases/download/v0.1.0/blast-radius_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "bf3ab5429444499192396909edb82a529c03d2921e1e8360025a257276ee3907"

      def install
        bin.install "blast-radius"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/blast-radius/releases/download/v0.1.0/blast-radius_0.1.0_Darwin_arm64.tar.gz"
      sha256 "b5f974dcfb7ee1a066c9950f007cbe07b43a2269c9dbf6cca90820e15181537d"

      def install
        bin.install "blast-radius"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/blast-radius/releases/download/v0.1.0/blast-radius_0.1.0_Linux_x86_64.tar.gz"
      sha256 "958a789d08a3c554e511db5d0bc576390dccf837d1a41fc65d01cf01ebd5ea4b"
      def install
        bin.install "blast-radius"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/blast-radius/releases/download/v0.1.0/blast-radius_0.1.0_Linux_arm64.tar.gz"
      sha256 "f4363071e7a2c1816f4ce6ccd421044cdefe846989ee6122d6df28c449b8826b"
      def install
        bin.install "blast-radius"
      end
    end
  end

  test do
    system "#{bin}/blast-radius --help"
  end
end
