# typed: false
# frozen_string_literal: true

# This file was generated by CloudNecromancer release automation.
class Cloudnecromancer < Formula
  desc "Reconstruct point-in-time AWS infrastructure snapshots by replaying CloudTrail events"
  homepage "https://github.com/pfrederiksen/cloudnecromancer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.1.0/cloudnecromancer_v0.1.0_darwin_amd64.tar.gz"
      sha256 "7cba61b3c2f78dddbbdf05df42e15de92e2538b8c985aeaf0808d25125da036d"

      def install
        bin.install "cloudnecromancer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.1.0/cloudnecromancer_v0.1.0_darwin_arm64.tar.gz"
      sha256 "c9a3abc8b2d8ef75e3860a02378f4031597e536a0e8689abc6e8f0ba93d0214e"

      def install
        bin.install "cloudnecromancer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.1.0/cloudnecromancer_v0.1.0_linux_amd64.tar.gz"
      sha256 "34380e810d1cfdddffc384c14b77ec50330b5fdb4d59a12b6892d509e1e2ea3d"
      def install
        bin.install "cloudnecromancer"
      end
    end
  end

  test do
    system "#{bin}/cloudnecromancer", "--quiet", "--help"
  end
end
