# typed: false
# frozen_string_literal: true

# This file was generated by CloudNecromancer release automation.
class Cloudnecromancer < Formula
  desc "Reconstruct point-in-time AWS infrastructure snapshots by replaying CloudTrail events"
  homepage "https://github.com/pfrederiksen/cloudnecromancer"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.2.0/cloudnecromancer_v0.2.0_darwin_amd64.tar.gz"
      sha256 "180ecef0bbb4c2e3712d38709690237c2adbe302bd768f9aee4af2b85931f395"

      def install
        bin.install "cloudnecromancer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.2.0/cloudnecromancer_v0.2.0_darwin_arm64.tar.gz"
      sha256 "7fe0fc20ef23067910768d190df2fa2d0cf9cc24c449bfda3feb3eba7a2b1d30"

      def install
        bin.install "cloudnecromancer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/cloudnecromancer/releases/download/v0.2.0/cloudnecromancer_v0.2.0_linux_amd64.tar.gz"
      sha256 "08d40f94c69fd84b9000de70ee559fea9fd15c82b11aa0e36634a59b673457f3"
      def install
        bin.install "cloudnecromancer"
      end
    end
  end

  test do
    system "#{bin}/cloudnecromancer", "--quiet", "--help"
  end
end
