# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configdiff < Formula
  desc "Semantic, human-grade diffs for YAML/JSON/HCL configuration files"
  homepage "https://github.com/pfrederiksen/configdiff"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.0/configdiff_0.1.0_darwin_x86_64.tar.gz"
      sha256 "e53b2e14a7b6a494623bfd9daa9a26dcdbbd48e860d6385e476bd02910ec52e0"

      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.0/configdiff_0.1.0_darwin_arm64.tar.gz"
      sha256 "1bef95b2c5fecdabec9c4ab4797fc493fee6556091bb3f564178cfa0ee131d4d"

      def install
        bin.install "configdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.0/configdiff_0.1.0_linux_x86_64.tar.gz"
      sha256 "d9db64e9a757b3fdf2b96ae30c8536797673a69cf2196a2526dbcb8fa6446eda"
      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.0/configdiff_0.1.0_linux_armv6.tar.gz"
      sha256 "1e53a2b55c0a88703aab804e14712fc2dbc1090d351c66c3450570bb3f8b484a"
      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.0/configdiff_0.1.0_linux_arm64.tar.gz"
      sha256 "8f88b3ebd38404c0bf18a3242116d924640b118896f2ada263c06d18c82615ab"
      def install
        bin.install "configdiff"
      end
    end
  end

  test do
    system "#{bin}/configdiff version"
  end
end
