# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configdiff < Formula
  desc "Semantic, human-grade diffs for YAML/JSON/HCL configuration files"
  homepage "https://github.com/pfrederiksen/configdiff"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.1/configdiff_0.1.1_darwin_x86_64.tar.gz"
      sha256 "73211a5f384438cfa5eb4d176db22553a03a2e3bee45f85092e61dcc527e812b"

      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.1/configdiff_0.1.1_darwin_arm64.tar.gz"
      sha256 "86b156ac7ba9205f7419bd8ccdd87856fb4c69e860a4ec1457c10d4c8204f420"

      def install
        bin.install "configdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.1/configdiff_0.1.1_linux_x86_64.tar.gz"
      sha256 "0193d96c285cd42d2fdd2ef8b2e430388e9225aedc1c0c14485bde591d374e62"
      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.1/configdiff_0.1.1_linux_armv6.tar.gz"
      sha256 "2730ef43b29ff5e4708acbd274dd17e8d31ab1a7a1fa29e960b3cacec87dfc80"
      def install
        bin.install "configdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/configdiff/releases/download/v0.1.1/configdiff_0.1.1_linux_arm64.tar.gz"
      sha256 "f08cb355acef8943238bff3884376a2e604bbb03b1474bfa152e7ef9dcb216ea"
      def install
        bin.install "configdiff"
      end
    end
  end

  test do
    system "#{bin}/configdiff version"
  end
end
