# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CostBlame < Formula
  desc "Local-first CLI to attribute AWS cost spikes to services, tags, and likely resources"
  homepage "https://github.com/pfrederiksen/cost-blame"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.0/cost-blame_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "6b8d4449bc30df0df3bd4febd04ad3468ee2b2d2f7e483d1b69f1017353d28e3"

      def install
        bin.install "cost-blame"
      end
    end
    on_arm do
      url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.0/cost-blame_0.2.0_Darwin_arm64.tar.gz"
      sha256 "25455256b62955d2be7b10cd4d557b4def5ad2e6b83ee90bf71074b3f13f6b92"

      def install
        bin.install "cost-blame"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.0/cost-blame_0.2.0_Linux_x86_64.tar.gz"
        sha256 "503f31d99dacfc5c4f54f708f29c8d260012830918446eb1340fd97a89e1c559"

        def install
          bin.install "cost-blame"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.0/cost-blame_0.2.0_Linux_arm64.tar.gz"
        sha256 "810f22443214cbd639e279f7b04af48f59a4f5ca3bf935a5a33aa7e1386e3ada"

        def install
          bin.install "cost-blame"
        end
      end
    end
  end

  test do
    system "#{bin}/cost-blame", "--help"
  end
end
