# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CostBlame < Formula
  desc "Local-first CLI to attribute AWS cost spikes to services, tags, and likely resources"
  homepage "https://github.com/pfrederiksen/cost-blame"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.1/cost-blame_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "36d7545829f2646f2e69c3a0fbff89da4b58e31a129974a1dcfbe9937417788c"

      def install
        bin.install "cost-blame"
      end
    end
    on_arm do
      url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.1/cost-blame_0.2.1_Darwin_arm64.tar.gz"
      sha256 "c557b6a76f75cc2c76cf8860f850010b21277d43a2416dbbde9cc6b938c6d74c"

      def install
        bin.install "cost-blame"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.1/cost-blame_0.2.1_Linux_x86_64.tar.gz"
        sha256 "e716780a813280feb8e725b64077b7e93367aee5e71d801ea8b84dc1c5ddc644"

        def install
          bin.install "cost-blame"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/cost-blame/releases/download/v0.2.1/cost-blame_0.2.1_Linux_arm64.tar.gz"
        sha256 "0f5efe7282ab6ee86f5a04a09385a4776fb8db794d147cd062775e04e709ac71"

        def install
          bin.install "cost-blame"
        end
      end
    end
  end

  test do
    system "#{bin}/cost-blame", "--help"
  end
end
