# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RivianLs < Formula
  desc "Production-quality TUI + headless CLI for monitoring Rivian vehicle telemetry"
  homepage "https://github.com/pfrederiksen/rivian-ls"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/pfrederiksen/rivian-ls/releases/download/v0.3.0/rivian-ls_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "0a76b499e3a41607f64461ab1bab433d0af29e495e71e770b067ba81225d0b1b"

      def install
        bin.install "rivian-ls"
      end
    end
    on_arm do
      url "https://github.com/pfrederiksen/rivian-ls/releases/download/v0.3.0/rivian-ls_0.3.0_Darwin_arm64.tar.gz"
      sha256 "4df5940668df6ccef12ec1d8a5a41a62cba748a058d43210a2bbe95c69e3c13c"

      def install
        bin.install "rivian-ls"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/rivian-ls/releases/download/v0.3.0/rivian-ls_0.3.0_Linux_x86_64.tar.gz"
        sha256 "a535511a1c8970995cfc78bc7a7fe19e0e0aa00149e3fcfbbf0836be742e10c8"

        def install
          bin.install "rivian-ls"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pfrederiksen/rivian-ls/releases/download/v0.3.0/rivian-ls_0.3.0_Linux_arm64.tar.gz"
        sha256 "f7b414847a3921e5ac31b30bb97fe95d0d17155d4549f4710239fbb3bc7c163e"

        def install
          bin.install "rivian-ls"
        end
      end
    end
  end

  test do
    system "#{bin}/rivian-ls", "version"
  end
end
