# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VgaEvents < Formula
  desc "CLI tool to check for newly-added VGA Golf state events"
  homepage "https://github.com/pfrederiksen/vga-events"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pfrederiksen/vga-events/releases/download/v0.7.0/vga-events_0.7.0_darwin_amd64.tar.gz"
      sha256 "c1c00709df8214fc7bf6be3d687af983c25369526bc6f299eab9fcb9fce85847"

      def install
        bin.install "vga-events"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pfrederiksen/vga-events/releases/download/v0.7.0/vga-events_0.7.0_darwin_arm64.tar.gz"
      sha256 "b289239292e8e69b1e422018d04eb55ba7f60e1701f396322cbbedbb1fa47f3a"

      def install
        bin.install "vga-events"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/vga-events/releases/download/v0.7.0/vga-events_0.7.0_linux_amd64.tar.gz"
      sha256 "715c080a4ca7ecc839d2b98adbf439031691efcdcc0bc9faa03170a954fa64d3"
      def install
        bin.install "vga-events"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pfrederiksen/vga-events/releases/download/v0.7.0/vga-events_0.7.0_linux_arm64.tar.gz"
      sha256 "9b2c315ef73ed4817b7ef1f1f07d90baabfad5f966f582847ae081e57dd627eb"
      def install
        bin.install "vga-events"
      end
    end
  end

  test do
    system "#{bin}/vga-events", "--help"
  end
end
